Repository manya-k/DECO3801---Data-Busters, pull requests merged in 2025-08, with the labels that each got.

#3 Main Game Screen Implementation & Refactor Unused Code (CSS Files Merged & Removed)
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/MainGameScreen.jsx
  frontend/src/assets/background.jpg
  frontend/src/index.css
  package-lock.json
Labels: Feature

#7 Add PR template
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: documentation

#6 Update readme
  README.md
Labels: documentation

#24 Build backend with Django and Enable backend API endpoints (CORS) for frontend integration
  .gitignore
  README.md
  backend/README.md
  backend/api/__init__.py
  backend/api/data/static_stories.json
  backend/api/urls.py
  backend/api/views.py
  backend/core/__init__.py
  backend/core/logic.py
  backend/core/urls.py
  backend/core/views.py
  backend/images/__init__.py
  backend/images/generate.py
  backend/llm/__init__.py
  backend/llm/ollama_interface.py
  backend/manage.py
  backend/memory_sim/__init__.py
  backend/memory_sim/settings.py
  backend/memory_sim/urls.py
  backend/memory_sim/wsgi.py
  backend/rag/__init__.py
  backend/rag/prompts.py
  backend/rag/retrieve.py
  backend/requirements.txt
Labels: Task

#26 Temp
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/BasePage/BasePage.jsx
  frontend/src/components/Button/Button.css
Labels: Task
